[build]
  command = "npm run build"
  publish="public/"
  
  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
  [[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
